;███████████████████████████████████████
;This is a file defined Turrent .
;
;EXAMPLE
;	Turrent_1_1    DB     "	  ████	 	",0
;	Turrent_1_2    DB     "	██	  ██ 	",0
;	Turrent_1_3    DB     "	  ██    ██	",0
;	Turrent_1_4    DB     "		██	  ██",0
;	Turrent_1_5    DB     "		█ ██████",0
;	Turrent_1_6    DB     "		█ 		",0
;	Turrent_1_7    DB     "		█  		",0
;
;███████████████████████████████████████

.Data