;	Version 3
.Code



	StartUpLogo 	MACRO
		CLS
		SettingColor 	gray
		Translate		0,0
		GraphDisplay 	StartUp_0
		GraphDisplay 	StartUp_1
		GraphDisplay 	StartUp_2
		GraphDisplay 	StartUp_3
		GraphDisplay 	StartUp_4
		GraphDisplay 	StartUp_5
		GraphDisplay 	StartUp_6
		GraphDisplay 	StartUp_7
		GraphDisplay 	StartUp_8
		GraphDisplay 	StartUp_9
		GraphDisplay 	StartUp_10
		GraphDisplay 	StartUp_11
		GraphDisplay 	StartUp_12
		GraphDisplay 	StartUp_13
		GraphDisplay 	StartUp_14
		GraphDisplay 	StartUp_15
		GraphDisplay 	StartUp_16
		GraphDisplay 	StartUp_17
		GraphDisplay 	StartUp_18
		GraphDisplay 	StartUp_19
		GraphDisplay 	StartUp_20
		GraphDisplay 	StartUp_21
		GraphDisplay 	StartUp_22
		GraphDisplay 	StartUp_23
		GraphDisplay 	StartUp_24
		GraphDisplay 	StartUp_25
		GraphDisplay 	StartUp_26
		GraphDisplay 	StartUp_27
		GraphDisplay 	StartUp_28
		GraphDisplay 	StartUp_29
		Translate 0,0
		AnyKeyToContinue
		ENDM
		

	StartUp_0 	DB "¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p",0
	StartUp_1 	DB "¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p",0
	StartUp_2 	DB "¢p¢p¢p¢p¢p¢p¢p¢p                    ¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p  ¢p¢p¢p¢p¢p¢p¢p¢p        ¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p",0
	StartUp_3 	DB "¢p¢p¢p¢p¢p¢p¢p¢p    ¢p        ¢p    ¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p      ¢p¢p¢p¢p¢p  ¢p              ¢p    ¢p¢p            ¢p¢p¢p¢p",0
	StartUp_4 	DB "¢p¢p¢p¢p    ¢p¢p  ¢p¢p¢p    ¢p¢p¢p  ¢p¢p¢p¢p¢p      ¢p¢p¢p      ¢p¢p¢p¢p  ¢p              ¢p    ¢p    ¢p¢p¢p    ¢p¢p¢p¢p",0
	StartUp_5 	DB "¢p¢p¢p¢p    ¢p¢p  ¢p¢p¢p    ¢p¢p¢p  ¢p¢p¢p¢p¢p        ¢p¢p      ¢p¢p¢p¢p  ¢p    ¢p  ¢p    ¢p    ¢p    ¢p¢p¢p    ¢p¢p¢p¢p",0
	StartUp_6 	DB "¢p¢p¢p¢p      ¢p¢p¢p¢p¢p    ¢p¢p¢p¢p¢p¢p¢p¢p    ¢p¢p  ¢p  ¢p    ¢p¢p¢p¢p  ¢p  ¢p¢p  ¢p¢p  ¢p    ¢p    ¢p¢p¢p¢p¢p¢p¢p¢p¢p",0
	StartUp_7 	DB "¢p¢p¢p¢p            ¢p¢p    ¢p            ¢p  ¢p¢p¢p  ¢p  ¢p¢p    ¢p¢p¢p  ¢p  ¢p¢p  ¢p¢p  ¢p    ¢p    ¢p¢p¢p¢p¢p¢p¢p¢p¢p",0
	StartUp_8 	DB "¢p¢p¢p¢p    ¢p¢p¢p  ¢p¢p    ¢p¢p    ¢p¢p¢p¢p  ¢p¢p¢p  ¢p  ¢p¢p    ¢p¢p¢p  ¢p  ¢p¢p  ¢p¢p  ¢p    ¢p¢p    ¢p¢p¢p¢p¢p¢p¢p¢p",0
	StartUp_9 	DB "¢p¢p¢p¢p    ¢p¢p¢p  ¢p¢p    ¢p¢p    ¢p¢p¢p¢p          ¢p  ¢p¢p¢p    ¢p¢p  ¢p¢p¢p¢p  ¢p¢p¢p¢p    ¢p¢p¢p    ¢p¢p¢p¢p¢p¢p¢p",0
	StartUp_10 	DB "¢p¢p¢p¢p    ¢p¢p¢p  ¢p¢p    ¢p¢p    ¢p¢p¢p    ¢p¢p¢p  ¢p  ¢p¢p¢p    ¢p¢p  ¢p¢p¢p¢p  ¢p¢p¢p¢p    ¢p¢p¢p¢p    ¢p¢p¢p¢p¢p¢p",0
	StartUp_11 	DB "¢p¢p¢p¢p    ¢p¢p¢p  ¢p¢p    ¢p¢p    ¢p¢p¢p    ¢p¢p¢p  ¢p  ¢p¢p¢p¢p    ¢p  ¢p¢p¢p¢p  ¢p¢p¢p¢p    ¢p¢p¢p¢p¢p    ¢p¢p¢p¢p¢p",0
	StartUp_12 	DB "¢p¢p¢p¢p            ¢p¢p    ¢p¢p    ¢p¢p    ¢p¢p¢p¢p  ¢p  ¢p¢p¢p¢p    ¢p  ¢p¢p¢p¢p  ¢p¢p¢p¢p    ¢p¢p¢p¢p¢p¢p    ¢p¢p¢p¢p",0
	StartUp_13 	DB "¢p¢p¢p¢p            ¢p¢p    ¢p¢p    ¢p¢p    ¢p¢p¢p¢p  ¢p  ¢p¢p¢p¢p¢p      ¢p¢p¢p¢p  ¢p¢p¢p¢p    ¢p¢p¢p¢p¢p¢p¢p  ¢p¢p¢p¢p",0
	StartUp_14 	DB "¢p¢p¢p¢p    ¢p¢p¢p  ¢p¢p    ¢p¢p    ¢p¢p  ¢p¢p    ¢p  ¢p  ¢p¢p¢p¢p¢p      ¢p¢p¢p¢p  ¢p¢p¢p¢p    ¢p  ¢p¢p¢p¢p¢p  ¢p¢p¢p¢p",0
	StartUp_15 	DB "¢p¢p¢p¢p    ¢p¢p¢p  ¢p¢p    ¢p¢p    ¢p¢p  ¢p¢p¢p  ¢p  ¢p  ¢p¢p¢p¢p¢p¢p    ¢p¢p¢p¢p  ¢p¢p¢p¢p    ¢p    ¢p¢p¢p    ¢p¢p¢p¢p",0
	StartUp_16 	DB "¢p¢p¢p¢p    ¢p¢p¢p  ¢p¢p    ¢p¢p    ¢p¢p¢p¢p¢p¢p  ¢p  ¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p  ¢p¢p¢p¢p    ¢p¢p            ¢p¢p¢p¢p",0
	StartUp_17 	DB "¢p¢p¢p¢p    ¢p¢p    ¢p¢p    ¢p¢p    ¢p¢p¢p¢p¢p    ¢p  ¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p      ¢p¢p¢p    ¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p",0
	StartUp_18 	DB "¢p¢p¢p¢p    ¢p¢p      ¢p    ¢p                    ¢p  ¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p          ¢p¢p    ¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p",0
	StartUp_19 	DB "¢p¢p¢p¢p    ¢p        ¢p    ¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p  ¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p    ¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p",0
	StartUp_20 	DB "¢p¢p¢p¢p    ¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p  ¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p    ¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p",0
	StartUp_21 	DB "¢p¢p¢p¢p    ¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p    ¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p",0
	StartUp_22 	DB "¢p¢p¢p¢p    ¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p        ¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p",0
	StartUp_23 	DB "¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p",0
	StartUp_24 	DB "¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p",0
	StartUp_25 	DB "¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p                                      ¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p",0
	StartUp_26 	DB "¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¡m¡iThe Adventure Starts From Here¡j¡n¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p",0
	StartUp_27 	DB "¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p                                      ¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p",0
	StartUp_28 	DB "¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p",0
	StartUp_29 	DB "¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p¢p",0